import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  collectionModal,
}: {
  children: React.ReactNode,
  collectionModal: React.ReactNode,
}) {
  return (
    <html lang="en">
      <body>
        <div>HEADER</div>
        <main className="container p-4">{children}</main>
        {collectionModal}
      </body>
    </html>
  )
}
