import { IHeaderLink } from '@/components/header/types';
import './globals.css'
import Header from '@/components/header/Header';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const links: IHeaderLink[] = [{
  href: '/',
  title: 'Home',
  isPublic: true,
},
{
  href: '/collection/new',
  title: 'New collection',
  isPublic: true,
}];

export default function RootLayout({
  children,
  collectionModal,
}: {
  children: React.ReactNode,
  collectionModal: React.ReactNode,
}) {
  return (
    <html lang="en">
      <body>
        <Header links={links} />
        <main className="container p-4 mx-auto">{children}</main>
        {collectionModal}
      </body>
    </html>
  )
}
